[workspace]
resolver = "2"
members = ["check"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.98.1"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
amplify = "=4.8.1"
hex = "=0.4.3"
o2a-demo-core = { version = "=0.1.0", path = "../../crates/o2a-demo-core" }
rgb-api = "=0.11.1"
rgb-consensus = "=0.11.1"
rgb-ops = "=0.11.1"
rgb-psbt-utils = "=0.11.1"
rgb-schemas = "=0.11.1"
rgb-strict-encoding = "=1.0.4"
rgb-strict-types = "=1.0.4"
serde_json = "=1.0.140"
