[package]
name = "o2a-demo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "o2a-demo"
path = "src/main.rs"

[dependencies]
amplify.workspace = true
anyhow.workspace = true
bp-std.workspace = true
hex.workspace = true
o2a-demo-core.workspace = true
o2a-demo-rgb.workspace = true
rgb-persist-fs.workspace = true
rgb-psbt.workspace = true
rgb-runtime.workspace = true
rgb-std.workspace = true
strict_encoding.workspace = true
strict_types.workspace = true
